version: "3"
services:
  practica:
    restart: always
    ports:
      - "8443:8443"
    networks:
      - conexionBBDD-network
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    restart: on-failure
    ports:
      - "5000:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      - conexionBBDD-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=web_fase_1  

networks:
  conexionBBDD-network: 